---
kind: ConfigMap
apiVersion: v1
metadata:
  name: loginapp
  namespace: auth
data:
  config.yaml: |
    debug: false
    client_id: "login"
    client_secret: 4TORGiNV9M54BTk1v7dNuFSaI6hUjfjr
    issuer_url: "https://dex.k8s.example.org/dex"
    issuer_root_ca: "/etc/ssl/ca.pem"
    redirect_url: "https://login.k8s.example.org/callback"
    listen: "http://0.0.0.0:5555"
    disable_choices: false
    extra_scopes: "groups"
    app_name: "Kubernetes Auth"
